---
name: Python Base Image
version: dev
slug: base-python
description: Docker Python base images used by Home Assistant Community Add-ons.
url: https://github.com/erik73/addon-base-python
arch:
  - aarch64
  - amd64
